### ISSUE TITLE
Laravel5 MySQL8.0 NO_AUTO_CREATE_USERのSQL_MODE エラー対策

### ISSUE THREAD

**Issue by ucan-lab** [ucan-lab/vagrant-laravel55#5]
## エラー

```
$ php artisan migrate
In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER' (SQL: sel
  ect * from information_schema.tables where table_schema = microposts and table_name = migrations)


In MySqlConnector.php line 150:

  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_CREATE_USER'
```

**Comment by ucan-lab** [comment]
## 対策

`config/database.php`

```
        'mysql' => [
            'strict' => false,
        ],
```

`strict` を false に変更すればokです。
新しくLaravelインストールしたものはデフォルトでfalseになってるっぽいです。
以前から使ってるLaravelでMySQL8.0にバージョンアップしたときにエラーになりそうです。

## 参考

- https://laracasts.com/discuss/channels/laravel/help-about-mysql-80-problem
- https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html

**Comment by ucan-lab** [comment]
https://qiita.com/ucan-lab/items/2a482a9537dcc5daeb97

**Comment by Apollo725** [comment]
Great, https://laracasts.com/discuss/channels/laravel/help-about-mysql-80-problem 
This can solve my problem, Thanks.

**Comment by sopedro** [comment]
Great @ucan-lab . It solves my problem too. Many thanks.

**Comment by AungPhyoKywe** [comment]
I change in databases.php
 'mysql' => [
          
            'strict' => false,
        
        ],

**Comment by thaifani** [comment]
change 
,
'strict' => false ,

**Comment by wincodes** [comment]
Thanks guys 

'strict' => false

Worked for me

**Comment by osamasado** [comment]
@wincodes  I have the same issue with drupal project, but I do not know where to find this file  databases.php, can you help me please?

**Comment by gideonp** [comment]
Dōmo arigatō ucan rabo
